package wizard.models;

import net.is_bg.ltf.db.common.interfaces.IAbstractModel;


/***This file is generated by LAK GenerateUtils...*/
public class DskFileTypeReg implements IAbstractModel{


/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**member variables...*/
	private long    filetyperegid;
	private String  type;
	private String  description;
	private long id;


	/**getters & setters*/
	public long getFiletyperegid(){
		return filetyperegid;
	}
	public void setFiletyperegid(long filetyperegid){
		this.filetyperegid = filetyperegid;
	}
	public String getType(){
		return type;
	}
	public void setType(String type){
		this.type = type;
	}
	public String getDescription(){
		return description;
	}
	public void setDescription(String description){
		this.description = description;
	}
	@Override
	public long getId() {
		// TODO Auto-generated method stub
		return id;
	}
	@Override
	public long getIndex() {
		// TODO Auto-generated method stub
		return 0;
	}
	@Override
	public void setId(long arg0) {
		// TODO Auto-generated method stub
		id  =  arg0;
	}
	@Override
	public void setIndex(long arg0) {
		// TODO Auto-generated method stub
		
	}
}